### PR TITLE
Add Order instances

### PR DESCRIPTION
**Pull request by tbrown1979**
Lots of repetition doing `Order.from(_.compareTo(_))` but I'm not sure if there's a better way..

### CODE REVIEW

**Comment by tbrown1979** [comment]
@ChristopherDavenport I'll make that change sometime today/tomorrow. Nice catch!

**Comment by tbrown1979** [comment]
@ChristopherDavenport What should I name these instances with the current structure of the project? `HashWithOrder`?

**Comment by ChristopherDavenport** [comment]
We can leave them as is for now. I'm thinking that due to the nature of building these it may be better to separate on time types and all instances for a particular type in a file. However I think that can wait for a later PR.

**Comment by tbrown1979** [comment]
@ChristopherDavenport Let me know if that looks good to you 😄

**Pull request merged**
