### PR TITLE
Add ZoneOffset instances

### PR DESCRIPTION
**Pull request by nigredo-tori**

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Not entirely sure I am following MiMa on the issue with the new trait mixed in.

**Comment by nigredo-tori** [comment]
From when this check [was implemented](https://github.com/lightbend/migration-manager/issues/118#issuecomment-227548644):
> However, a binary incompatibility arise when a new trait type with concrete or abstract methods **is inherited by another, already existing, trait**. The reason being that implementers of the existing trait will miss the forwarders to the methods in the new trait's implementation class, and this situation can lead to linkage errors (specifically, an `AbstractMethodError`).

However, I don't see why this method (val) is considered abstract.

**Comment by nigredo-tori** [comment]
`scalac` does, indeed, compile this `val` to an abstract method in the `zoneoffset` interface. Makes sense if you think about it - there's no way to implement a getter since there is no way to store a reference inside an interface.

I'll just move the instance to the companion object, and forward it manually - this is ugly, but it should keep MiMa happy. Same goes for #51.

**Comment by ChristopherDavenport** [comment]
Other option is we can just bump version. I'm thinking it may be worth it to get these improvements in place.

**Comment by nigredo-tori** [comment]
Actually, scratch that. Just remembered that Scala 2.11 has to support Java 7 - which means no default methods, which means we're stuck.

> Other option is we can just bump version.

Sure. I'll roll my instances into one in #51, then - this doesn't solve binary compatibility anyway.

**Comment by nigredo-tori** [comment]
I've taken the liberty to bump the version to 0.3.0-SNAPSHOT in this MR.

**Pull request merged**
